# Mod failure analysis
# Generates the mod analysis sheets in the final excel file
# requires failurelist.R to have run before it!

save_these=ls()


#generates al ist of the unique mod combinations, and counts the times they were made
mod_counts <-
        clean_raw %>% #data to pull from from failurelist.R
        group_by(Five_Prime_mod, Three_Prime_mod) %>% #group by 5' and 3' mod
        summarize(times_made = n()) %>% #count times exist, make new variable
        arrange(desc(times_made)) # sort via times_made

#generate a list of the unique mod combinations and count times they failed
mod_failure_counts <-
        clean_failure %>% #data to pull from, from failurelist.R
        group_by(Five_Prime_mod, Three_Prime_mod) %>% # group by 5' and 3' mod
        summarize(number_of_failures = n()) %>% #count times exist, make new variable
        arrange(desc(number_of_failures)) #sort via times_made

#put made counts and failure counts together, keeping ones that have no failures
mod_FR_raw <- merge(mod_counts, mod_failure_counts, all.x=TRUE)
#convert NA's generated by mods haveing no failures to 0
mod_FR_raw$number_of_failures[is.na(mod_FR_raw[,4])] <- 0
#Add a failure rate variable to the data frame, sort by rate, and remove bad data
mod_FR <-
        mod_FR_raw %>% #data fraome to work on
        mutate(failure_rate = number_of_failures/times_made) %>% #new failure rate variable
        #its the number_of_failures variable/times_made variable
        arrange(desc(number_of_failures))  #arrange by failure rate
        #remove failure-rate = 1 mod combos

#the below scripts are almost carbon copies of the one above, but instead of working
#on mod combos they simply work on 5' mod or 3' mod.
###

mod5_counts <-
        clean_raw %>%
        group_by(Five_Prime_mod) %>%
        summarize(times_made = n()) %>%
        arrange(desc(times_made))

mod5_failure_counts <-
        clean_failure %>%
        group_by(Five_Prime_mod) %>%
        summarize(number_of_failures = n()) %>%
        arrange(desc(number_of_failures))

mod5_FR_raw <- merge(mod5_counts, mod5_failure_counts, all.x=TRUE)

mod5_FR_raw$number_of_failures[is.na(mod5_FR_raw[,3])] <- 0

mod5_FR <-
        mod5_FR_raw %>%
        mutate(failure_rate = number_of_failures/times_made) %>%
        arrange(desc(number_of_failures))


###

mod3_counts <-
        clean_raw %>%
        group_by(Three_Prime_mod) %>%
        summarize(times_made = n()) %>%
        arrange(desc(times_made))

mod3_failure_counts <-
        clean_failure %>%
        group_by(Three_Prime_mod) %>%
        summarize(number_of_failures = n()) %>%
        arrange(desc(number_of_failures))

mod3_FR_raw <- merge(mod3_counts, mod3_failure_counts, all.x=TRUE)

mod3_FR_raw$number_of_failures[is.na(mod3_FR_raw[,3])] <- 0

mod3_FR <-
        mod3_FR_raw %>%
        mutate(failure_rate = number_of_failures/times_made) %>%
        arrange(desc(number_of_failures)) 


###

class(mod_FR) <- "data.frame"
class(mod5_FR) <- "data.frame"
class(mod3_FR) <- "data.frame"


if (data_size == 1) { #if large:
        modoutputname <- paste(outputfolder, "\\", outputname, "_mod", ".xlsx", sep="") #.csv ext
        write.xlsx(mod_FR,
                   file=modoutputname,
                   sheetName="Both Mod Failure Rate",
                   row.names=FALSE,
                   append=TRUE)
        
        write.xlsx(mod5_FR,
                   file=modoutputname,
                   sheetName="Five Prime Mod Failure Rate",
                   row.names=FALSE,
                   append=TRUE)
        
        write.xlsx(mod3_FR,
                   file=modoutputname,
                   sheetName="Three Prime Mod Failure Rate",
                   row.names=FALSE,
                   append=TRUE) #converts NA's to blank boxes
} else { #if small data file:
        write.xlsx(mod_FR,
                   file=outputnamexlsx,
                   sheetName="Both Mod Failure Rate",
                   row.names=FALSE,
                   append=TRUE)
        
        write.xlsx(mod5_FR,
                   file=outputnamexlsx,
                   sheetName="Five Prime Mod Failure Rate",
                   row.names=FALSE,
                   append=TRUE)
        
        write.xlsx(mod3_FR,
                   file=outputnamexlsx,
                   sheetName="Three Prime Mod Failure Rate",
                   row.names=FALSE,
                   append=TRUE)#allow it to append to existing excel file.
        
}

full_list <- ls()
delete <- full_list[!full_list %in% save_these]
rm(list=delete, delete, full_list)

